[package]
name = "siem"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
nom = "7.1"
tracing = "0.1"
tracing-subscriber = "0.3"
rusqlite = { version = "0.31", features = ["bundled", "bundled-sqlcipher"] }
chrono = { version = "0.4", features = ["serde"] }
csv = "1.3"
flate2 = "1.0"
compact_str = { version = "0.8", features = ["serde"] }
crossbeam-channel = "0.5"
bloomfilter = "1.0"
opentelemetry = "0.24"
dotenvy = "0.15"
memmap2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
tracing-opentelemetry = "0.25"
opentelemetry-otlp = { version = "0.17", features = ["grpc-tonic"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "parser_bench"
harness = false

[build-dependencies]
cc = "1.0"

[profile.release]
debug = true

[profile.dev]
opt-level = 1

[profile.bench]
opt-level = 3

[profile.test]
opt-level = 1

[workspace]
members = ["."]
